categories: [Tools]
description: CSP 2
name: csp2
owner: jpayne
exclude:
 - test-data/
 - .git/
 - .gitignore/
 - LICENSE
 - README.md
 - tool_test_output.html
 - tool_test_output.json
 - .python-version
 - job_conf_sample.yml
 - job_conf.yml
 - CSP2